# Arthmetic Operation

In [1]:
import numpy as np
var=np.array([2,3,11,33,4])
varAdd=var+3
print(varAdd)

[ 5  6 14 36  7]


In [4]:
var1=np.array([2,3,11,33,4])
var2=np.array([2,3,44,5,6])
varAdd1=var1+var2
print(varAdd1)

[ 4  6 55 38 10]


In [6]:
var=np.array([2,3,11,33,4])
varAdd=var-3
print(varAdd)

var1=np.array([2,3,11,33,4])
var2=np.array([2,3,44,5,6])
varAdd1=var1-var2
print(varAdd1)

[-1  0  8 30  1]
[  0   0 -33  28  -2]


In [7]:
var=np.array([2,3,11,33,4])
varAdd=var*3
print(varAdd)

var1=np.array([2,3,11,33,4])
var2=np.array([2,3,44,5,6])
varAdd1=var1*var2
print(varAdd1)

[ 6  9 33 99 12]
[  4   9 484 165  24]


In [8]:
var=np.array([2,3,11,33,4])
varAdd=var/3
print(varAdd)

var1=np.array([2,3,11,33,4])
var2=np.array([2,3,44,5,6])
varAdd1=var1/var2
print(varAdd1)

[ 0.66666667  1.          3.66666667 11.          1.33333333]
[1.         1.         0.25       6.6        0.66666667]


In [9]:


var1=np.array([2,3,11,33,4])
var2=np.array([2,3,44,5,6])
var1+=var2
print(var1)

[ 4  6 55 38 10]


In [11]:
var=np.array([2,3,11,33,4])
varAdd=var%2
print(varAdd)

var1=np.array([2,3,11,33,4])
var2=np.array([2,3,44,5,6])
varAdd1=var1%var2
print(varAdd1)

[0 1 1 1 0]
[ 0  0 11  3  4]


# Artimetic Operation using Inbuit Function

In [13]:
var1=np.array([2,3,11,33,4])
var2=np.array([2,3,44,5,6])
varrAdd=np.add(var1,var2)
print(varrAdd)

[ 4  6 55 38 10]


In [14]:
var1=np.array([2,3,11,33,4])
var2=np.array([2,3,44,5,6])
varSubtract=np.subtract(var1,var2)
print(varSubtract)

[  0   0 -33  28  -2]


In [15]:
var1=np.array([2,3,11,33,4])
var2=np.array([2,3,44,5,6])
vardivide=np.divide(var1,var2)
print(vardivide)

[1.         1.         0.25       6.6        0.66666667]


In [19]:
var1=np.array([2,3,11,33,4])
var2=np.array([2,3,44,5,6])
varMultiply=np.multiply(var1,var2)
print(varMultiply)

[  4   9 484 165  24]


In [20]:
var1=np.array([2,3,11,33,4])
var2=np.array([2,3,44,5,6])
varMod=np.mod(var1,var2)
print(varMod)

[ 0  0 11  3  4]


In [21]:
var1=np.array([2,3,11,33,4])
var2=np.array([2,3,44,5,6])
varPower=np.power(var1,var2)
print(varPower)

[        4        27 285373457  39135393      4096]


In [32]:
var1=np.array([1,3,11,33,4])
var2=np.array([2,3,44,5,6])

var3=np.reciprocal(var1)
print(var3)
print()
a=3
varRecip=np.reciprocal(a)
print(varRecip)

[1 0 0 0 0]

0


# Arithmetic Operation on 2D Array

In [30]:


var1=np.array([[2,3,11,33,4],[526,3,3,4,44]])
var2=np.array([[2,3,10,3,10],[0,3,10,5,10]])

varrAdd2=var1+var2
print(varrAdd2)
print()
varrAdd3=np.add(var1,var2)
print(varrAdd2)

[[  4   6  21  36  14]
 [526   6  13   9  54]]

[[  4   6  21  36  14]
 [526   6  13   9  54]]


In [31]:
var1=np.array([[2,3,11,33,4],[526,3,3,4,44]])
var2=np.array([[2,3,10,3,10],[0,3,10,5,10]])

varrAdd2=var1*var2
print(varrAdd2)
print()
varrAdd3=np.multiply(var1,var2)
print(varrAdd2)

[[  4   9 110  99  40]
 [  0   9  30  20 440]]

[[  4   9 110  99  40]
 [  0   9  30  20 440]]
