# Data Type

In [1]:
import numpy as np
var =np.array([2,3,4,2])
print("Data Type ",var.dtype)#dtype attribute

Data Type  int32


In [6]:
var1 =np.array([2.0,3.9,33.5,4.3,2.0])
print("Data Type ",var1.dtype)#dtype attribute

Data Type  float64


In [8]:
var3 =np.array(["A","6"])
print("Data Type ",var3.dtype)#dtype =, u1 is string

Data Type  <U1


In [9]:
var3 =np.array(["A","6",5,5,3])
print("Data Type ",var3.dtype)#dtype = u11 

Data Type  <U11


In [13]:
x=np.array([1,3,4,5],dtype=np.int8)#Explict converting int32 to int8
print("Data Type :" ,x.dtype)

Data Type : int8


In [14]:
x1=np.array([1,3,4,5],dtype="f")#Explict converting int32 to to float32 using attribute
print("Data Type :" ,x1.dtype)
print(x1)

Data Type : float32
[1. 3. 4. 5.]


In [21]:
x2=np.array([1,3,4,5])
new =np.float32(x2)#Explict converting using function
print("Data Type :" ,new.dtype)
print(new)
print("Data Type :" ,x2.dtype)
print(x2)


Data Type : float32
[1. 3. 4. 5.]
Data Type : int32
[1 3 4 5]


In [19]:
x2=np.array([1,3,4,5])
new =np.float32(x2)
new_one=np.int_(new)#again Explict converting back using using function
print("Data Type :" ,new.dtype)
print(new)
print("Data Type :" ,new_one.dtype)
print(new_one)

Data Type : float32
[1. 3. 4. 5.]
Data Type : int32
[1 3 4 5]


In [22]:
x3=np.array([1,3,4,5])
new_1=x3.astype(float)#agar ham nhi chate ki fir se ham convert kare uske original type me toh ham astype function use kar sakte hai.
print(x3)
print(new_1)

[1 3 4 5]
[1. 3. 4. 5.]
