# Indexing in Numpy Array

In [2]:
import numpy as np
x1=np.array([1,3,4,5,11])
print(x1)
print(x1[3])

[ 1  3  4  5 11]
5


In [6]:
print(x2[-2,-2])#Negative Indexing

4


In [10]:
x3=np.array([[[33,1,4,5],[44,23,5,5]]])
print(x3[0,0,2],x3[0,1,3])

4 5


In [17]:
x4=np.array([[[[1,2,3,5],[33,1,4,5],[44,23,5,5]]]])
print(x4.shape)


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5,) + inhomogeneous part.

In [5]:
x4=np.random.randn(4,3,3,2)
print(x4)
print()
print(x4[0,2,2,1])
print()
print(x4[0,0,0,1])
print()
print(x4[1,2])

[[[[-0.98815623 -0.90827995]
   [ 0.45619573 -0.69450084]
   [-0.39449044  0.86189727]]

  [[-1.04001815  0.28130395]
   [-0.87277589 -0.53252224]
   [-0.54839094 -0.18517981]]

  [[-0.93622164  0.2818328 ]
   [-0.11233584 -0.48801543]
   [ 1.24057989  0.91698709]]]


 [[[-0.43987213 -0.52551334]
   [ 1.43413453 -0.00556105]
   [-2.64436779 -0.09002925]]

  [[-0.18969495 -0.61650918]
   [ 0.44152456  0.69919141]
   [-0.08977734 -1.92541351]]

  [[-1.27062566  0.90259039]
   [-0.07723171  0.95792897]
   [-1.37861148 -0.33707502]]]


 [[[ 0.06680476 -0.09135356]
   [ 1.71415566  0.63647901]
   [-0.27237825 -0.94698927]]

  [[ 0.91741975  0.1265189 ]
   [ 0.27070737  0.46752272]
   [ 2.2782881   0.40155866]]

  [[ 1.53194943 -0.69599418]
   [-0.18474411 -1.33170875]
   [-0.10288494  1.08098701]]]


 [[[ 0.03808745 -0.08194613]
   [ 0.44147761  0.87878143]
   [ 0.0642695   0.39657708]]

  [[ 0.53566566  0.32859723]
   [ 1.28863955 -2.47406423]
   [-0.91716073 -1.19073096]]

  [[-0.47739424

In [22]:
x5=np.random.randn(2,3,4)
print(x5)

[[[-0.47260508 -0.09838548 -1.10668745 -1.0885812 ]
  [ 0.49470072 -0.24703693 -0.6247354  -0.43665026]
  [-0.34506112  0.08709966  1.36290779  0.60051571]]

 [[-0.21403229  0.03875905  0.01656757 -0.07185811]
  [ 1.27449036 -0.16624328 -0.13622873 -1.02414121]
  [-0.63828698 -1.10258098 -0.60280698  0.45124881]]]
