# Iteration In Numpy 

In [4]:
import numpy as np
var1=np.array([2,5,3,8,5])
print(var1)
for i in var1:
    print(i)

[2 5 3 8 5]
2
5
3
8
5


In [7]:
var2=np.array([[3,2,8,9],[4,1,2,7]])
print(var2)
for i in var2:
    print(i)
    
for i in var2:
    for j in i:
        print(j)

[[3 2 8 9]
 [4 1 2 7]]
[3 2 8 9]
[4 1 2 7]
3
2
8
9
4
1
2
7


In [10]:
array3D=np.array([[[3,2,8,9],[4,1,2,7]]])
print(array3D)
for i in array3D:
    print(i)
    
for i in array3D:
    for j in i:
        for k in j:
            print(k)
            
    


[[[3 2 8 9]
  [4 1 2 7]]]
[[3 2 8 9]
 [4 1 2 7]]
3
2
8
9
4
1
2
7


In [12]:
my_arr=np.array([[[3,6,7,2],[3,9,0,5]]])
print(my_arr)

for i in np.nditer(my_arr):#nditer function to iterate on array
    print(i)

[[[3 6 7 2]
  [3 9 0 5]]]
3
6
7
2
3
9
0
5


In [15]:
my_arr=np.array([[[3,6,7,2],[3,9,0,5]]])
print(my_arr)

for i in np.nditer(my_arr,flags=['buffered'],op_dtypes=["s"]):#nditer function me ham 2nd parameter me ham apne dtype ko bhi change kar sakte ha, buffer hme eak extra space create kar ke deta hai jaha ham yeh iterated data store kar skate hai,op_dtype ke using ham ne datatype string rakha.
    print(i)

[[[3 6 7 2]
  [3 9 0 5]]]


TypeError: Field elements must be 2- or 3-tuples, got ''s''