# Math Function


np.min(x)
np.max(x)
np.argmin(x)
np.sqrt(x)
np.sin(x)
np.cos(x)
np.cumsum(x)

In [8]:
import numpy as np
x1=np.array([11,3,5,2,4,5,33,45,43,56])
print("Minium Number :",np.min(x1)," and the index is ",np.argmin(x1))
print("Maximun Number :",np.max(x1),np.argmax(x1))
print("Square Root :",np.sqrt(x1))

Minium Number : 2  and the index is  3
Maximun Number : 56 9
Square Root : [3.31662479 1.73205081 2.23606798 1.41421356 2.         2.23606798
 5.74456265 6.70820393 6.55743852 7.48331477]


In [12]:
x2=np.array([[2,34,4,6],[8,2,9,1]])
print(np.min(x2,axis=1))#axis 1 represent row and axis 0 represent column
print(np.min(x2,axis=0))

[2 1]
[2 2 4 1]


In [14]:
x3=np.array([[2,34,4,6],[8,2,9,1]])
print(np.max(x3,axis=1))
print(np.max(x3,axis=0))

[34  9]
[ 8 34  9  6]


In [16]:
x4=np.array([[1,2,3]])
print(np.sin(x4))
print(np.cos(x4))

[[0.84147098 0.90929743 0.14112001]]
[[ 0.54030231 -0.41614684 -0.9899925 ]]


In [18]:
print(np.cumsum(x4))#1,1+2,3+3=[1,3,3]

[1 3 6]
