# Special Numpy Array Inbuilt Function

1.Array filled with Zero with zero function

In [16]:
import numpy as np
arr_zero1=np.zeros(4)#1-Dimension
print(arr_zero1)

print()

arr_zero2=np.zeros((3,4))#2-Dimension
print(arr_zero2)

print()

arr_zeroN=np.zeros((1,2,3))#3-Dimension array
print(arr_zeroN)

print()
arr_zeroN=np.zeros((2,2,3))#3-Dimension array
print(arr_zeroN)


#With datatype
arr_zeroDT=np.zeros((2,3),dtype=int)
print(arr_zeroDT)

arr_zeroDT1=np.zeros((2,3),dtype=[('x','int'),('y','double')])
print(arr_zeroDT1)
print(arr_zeroDT1.dtype)


[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[[0. 0. 0.]
  [0. 0. 0.]]]

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]
[[0 0 0]
 [0 0 0]]
[[(0, 0.) (0, 0.) (0, 0.)]
 [(0, 0.) (0, 0.) (0, 0.)]]
[('x', '<i4'), ('y', '<f8')]


2. Array Filled with ones with ones function

In [17]:
arr_one1=np.ones(5)
print(arr_one1)

[1. 1. 1. 1. 1.]


In [19]:
array_2d = np.ones((2, 3))
print(array_2d)

array_2d_int = np.ones((2, 3), dtype=int)
print(array_2d_int)

array_mix_type = np.ones((2, 2), dtype=[('x', 'int'), ('y', 'float')])
print(array_mix_type)
print(array_mix_type.dtype)

[[1. 1. 1.]
 [1. 1. 1.]]
[[1 1 1]
 [1 1 1]]
[[(1, 1.) (1, 1.)]
 [(1, 1.) (1, 1.)]]
[('x', '<i4'), ('y', '<f8')]


3.Create Empty Array with Empty Function

In [25]:
arr_empty1=np.empty(4)
print(arr_empty1)#output me one dega kyu ki empty array me previous memory me jo data Save rehta hai wah aa jata hai.

arr_empty2=np.empty([2,3])
print(arr_empty2)

arr_empty2=np.empty((2,3))#same like above
print(arr_empty2)

arr_empty2=np.empty([2,3],dtype=int)
print(arr_empty2)


#Refer Docs
a = ([1,2,3], [4,5,6])                         # a is array-like
np.empty_like(a)

a = np.array([[1., 2., 3.],[4.,5.,6.]])
np.empty_like(a)


[1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1547344304        514          0]
 [         0          1          0]]


array([[1., 1., 1.],
       [1., 1., 1.]])

4.Range function

In [26]:
arr_rn=np.arange(4)
print(arr_rn)

[0 1 2 3]


5.Digional Element filled with ones eye Function

In [31]:
arr_dig1=np.eye(3)#1-Dimension
print(arr_dig)

print()

arr_dig2=np.eye(3,5)#2-Dimension
print(arr_dig2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


6.Array with space linearly in specified interval with linspace function

In [34]:
arr_ln=np.linspace(1,10,num=5)
print(arr_ln)

arr_ln2=np.linspace(0,20,num=5)
print(arr_ln2)

arr_ln3=np.linspace(1,3,num=8)
print(arr_ln3)

[ 1.    3.25  5.5   7.75 10.  ]
[ 0.  5. 10. 15. 20.]
[1.         1.28571429 1.57142857 1.85714286 2.14285714 2.42857143
 2.71428571 3.        ]


7.Random Modules and its Function

In [44]:
arr_rnd1=np.random.rand(4)#1-D 4 random value generate karega between 0-1,random module ke nadar rand function hai
print(arr_rnd)

arr_rnd2=np.random.rand(2,5)#2-D
print(arr_rnd2)


arr_randn=np.random.randn(5)#positive and negative number close to zero
print(arr_randn)

arr_randf=np.random.ranf(5)
print(arr_randf)

arr_randint=np.random.randint(3,8,5)#minium,maxium,total number
print(arr_randint)


[0.21753276 0.7875872  0.04282668 0.03043687]
[[0.38616351 0.21850583 0.46434025 0.61582356 0.13852426]
 [0.20930654 0.81220674 0.66758301 0.71396513 0.94060563]]
[ 1.3561264   0.4383215   0.44166219 -1.01931135 -1.13718989]
[0.13487823 0.61089187 0.60167693 0.95899758 0.33289646]
[6 4 7 6 3]
