# Slicing in Numpy Array

In [14]:
import numpy as np
v1=np.array([1,3,5,6,44,23,77,765,78])

print(v1[1:4])#start,Stop
print(v1[1:9:2])#start,stop,jump/step
print(v1[2:9:4])
print(v1[:7:2])
print(v1[1:])
print(v1[:5])


print(v1[:-1])#end at -1 index
print(v1[-1:])#start from -1
print(v1[::-1])#Reverse
print(v1[::1])
print(v1[::-2])




[3 5 6]
[  3   6  23 765]
[ 5 77]
[ 1  5 44 77]
[  3   5   6  44  23  77 765  78]
[ 1  3  5  6 44]
[  1   3   5   6  44  23  77 765]
[78]
[ 78 765  77  23  44   6   5   3   1]
[  1   3   5   6  44  23  77 765  78]
[78 77 44  5  1]


# Slicing in 2D

In [24]:
var2D=np.array([[3,3,5,2,7,8],[2,5,11,8,5,7],[6,2,9,8,1,5]])
print(var2D[0,1:])
print(var2D[0,0:6:2])
print(var2D[1,1:])
print(var2D[0:3,2])
print(var2D[0:2,2])
print(var2D[0:2,1:4])

[3 5 2 7 8]
[3 5 7]
[ 5 11  8  5  7]
[ 5 11  9]
[ 5 11]
[[ 3  5  2]
 [ 5 11  8]]
